definitions:
  user.LoginResp:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample server celler server.
  title: go_backend API
  version: 0.0.1
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: User login
      parameters:
      - description: username
        in: body
        name: username
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/user.LoginResp'
        "400":
          description: bad request
          schema:
            type: string
        "500":
          description: internal server error
          schema:
            type: string
      summary: User login
      tags:
      - User
swagger: "2.0"
